# Generated by Django 2.2.5 on 2020-12-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20201128_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=35.6736806, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=139.7725326, max_digits=15),
            preserve_default=False,
        ),
    ]
