# Generated by Django 3.1.4 on 2021-01-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20201208_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
