# Generated by Django 2.2.5 on 2020-12-20 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citymaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='area',
            field=models.CharField(max_length=200, verbose_name='延床面積'),
        ),
        migrations.AlterField(
            model_name='city',
            name='completion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citymaps.Completion', verbose_name='竣工年'),
        ),
        migrations.AlterField(
            model_name='city',
            name='floor',
            field=models.CharField(max_length=200, verbose_name='階数'),
        ),
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.CharField(max_length=500, verbose_name='完成イメージ'),
        ),
        migrations.AlterField(
            model_name='city',
            name='owner',
            field=models.CharField(max_length=100, verbose_name='事業主'),
        ),
        migrations.AlterField(
            model_name='city',
            name='source',
            field=models.CharField(max_length=500, verbose_name='出典元'),
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=100, verbose_name='建物名'),
        ),
        migrations.AlterField(
            model_name='city',
            name='url',
            field=models.CharField(max_length=500, verbose_name='リンク先'),
        ),
        migrations.AlterField(
            model_name='city',
            name='use',
            field=models.CharField(max_length=200, verbose_name='用途'),
        ),
    ]
